version: '3.9'

services:
  api:
    build:
      context: ./api
    env_file: 
      - .env
    ports:
      - "8001:8000"
    networks:
      - app-network

  web:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - api
    networks:              
      - app-network

networks:
  app-network:
    driver: bridge

