name: Deploy API to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image locally
        run: |
          docker build -t pruebaregistri.azurecr.io/cvae-api:${{ github.sha }} ./project/api

      - name: Login to Azure Container Registry
        run: az acr login --name pruebaregistri

      - name: Push Docker image to ACR
        run: docker push pruebaregistri.azurecr.io/cvae-api:${{ github.sha }}

      - name: Create Azure Web App (if not exists)
        run: |
          az webapp create \
            --resource-group Prueba \
            --plan miAppServicePlan \
            --name <TU_WEBAPP_NAME> \
            --deployment-container-image-name pruebaregistri.azurecr.io/cvae-api:${{ github.sha }} || echo "App already exists"

      - name: Configure Web App container settings
        run: |
          az webapp config container set \
            --name miWebApp \
            --resource-group Prueba \
            --docker-custom-image-name pruebaregistri.azurecr.io/cvae-api:${{ github.sha }} \
            --docker-registry-server-url https://pruebaregistri.azurecr.io

      - name: Restart Azure Web App
        run: az webapp restart --name miWebApp --resource-group Prueba
