name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build API Docker image
        run: docker build ./api --file ./project/api/Dockerfile --tag api-image:$(date +%s)

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Frontend Docker image
        run: docker build ./frontend --file ./project/frontend/Dockerfile --tag frontend-image:$(date +%s)
